import {useCallback,useEffect,useMemo,useState} from 'react'
import type {Session} from '@supabase/supabase-js'
import {supabase} from './lib/supabase'
import './Admin.css'

type View='dashboard'|'customers'|'kyc'|'payments'|'holdings'|'profits'|'withdrawals'|'compliance'|'ledger'|'audit'
type Profile={id:string;full_name:string;phone:string|null;role:string;kyc_status:string;created_at:string}
type Payment={id:string;user_id:string;method:string;transaction_id:string;amount:number;proof_path:string;status:string;created_at:string;profiles?:Profile|null}
type Investment={id:string;user_id:string;plan_name:string;principal:number;gold_grams:number;gold_price_per_bhori:number;purchased_at:string;active:boolean;profiles?:Profile|null}
type Withdrawal={id:string;user_id:string;amount:number;status:string;created_at:string;profiles?:Profile|null;investments?:{plan_name:string}|null}
type Hold={id:string;user_id:string;reason:string;active:boolean;created_at:string;profiles?:Profile|null}
type Profit={id:string;user_id:string;amount:number;basis:string;created_at:string;profiles?:Profile|null}
type Ledger={id:number;user_id:string;entry_type:string;amount:number;gold_grams:number;description:string;created_at:string;profiles?:Profile|null}
type Audit={id:number;action:string;entity_type:string;entity_id:string;metadata:Record<string,unknown>;created_at:string;profiles?:Profile|null}
type Kyc={id:string;user_id:string;date_of_birth:string;present_address:string;occupation:string;nominee_name:string;nominee_relation:string;status:string;submitted_at:string;profiles?:Profile|null}
const labels:Record<View,string>={dashboard:'ড্যাশবোর্ড',customers:'কাস্টমার',kyc:'KYC যাচাই',payments:'পেমেন্ট অনুমোদন',holdings:'গোল্ড হোল্ডিংস',profits:'প্রফিট ঘোষণা',withdrawals:'উত্তোলন রিভিউ',compliance:'কমপ্লায়েন্স',ledger:'ট্রানজ্যাকশন লেজার',audit:'অডিট ও রিপোর্ট'}
const money=(n:number)=>`৳${Number(n||0).toLocaleString('bn-BD')}`

export default function AdminApp(){
 const[session,setSession]=useState<Session|null>(null),[allowed,setAllowed]=useState<boolean|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState<View>('dashboard'),[query,setQuery]=useState(''),[selectedCustomer,setSelectedCustomer]=useState<Profile|null>(null)
 const[profiles,setProfiles]=useState<Profile[]>([]),[payments,setPayments]=useState<Payment[]>([]),[investments,setInvestments]=useState<Investment[]>([]),[withdrawals,setWithdrawals]=useState<Withdrawal[]>([]),[holds,setHolds]=useState<Hold[]>([]),[profits,setProfits]=useState<Profit[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[audits,setAudits]=useState<Audit[]>([]),[kycSubs,setKycSubs]=useState<Kyc[]>([])
 const load=useCallback(async()=>{setError('');const results=await Promise.all([
  supabase.from('profiles').select('*').order('created_at',{ascending:false}),
  supabase.from('payment_requests').select('*,profiles!payment_requests_user_id_fkey(*)').order('created_at',{ascending:false}),
  supabase.from('investments').select('*,profiles!investments_user_id_fkey(*)').order('purchased_at',{ascending:false}),
  supabase.from('withdrawal_requests').select('*,profiles!withdrawal_requests_user_id_fkey(*),investments(plan_name)').order('created_at',{ascending:false}),
  supabase.from('compliance_holds').select('*,profiles!compliance_holds_user_id_fkey(*)').order('created_at',{ascending:false}),
  supabase.from('profit_declarations').select('*,profiles!profit_declarations_user_id_fkey(*)').order('created_at',{ascending:false}),
  supabase.from('transaction_ledger').select('*,profiles!transaction_ledger_user_id_fkey(*)').order('created_at',{ascending:false}),
  supabase.from('admin_audit_logs').select('*,profiles!admin_audit_logs_admin_id_fkey(*)').order('created_at',{ascending:false}).limit(300),
  supabase.from('kyc_submissions').select('*,profiles!kyc_submissions_user_id_fkey(*)').order('submitted_at',{ascending:false})
 ]);const first=results.find(x=>x.error);if(first?.error)setError(first.error.message);setProfiles((results[0].data||[]) as Profile[]);setPayments((results[1].data||[]) as Payment[]);setInvestments((results[2].data||[]) as Investment[]);setWithdrawals((results[3].data||[]) as Withdrawal[]);setHolds((results[4].data||[]) as Hold[]);setProfits((results[5].data||[]) as Profit[]);setLedger((results[6].data||[]) as Ledger[]);setAudits((results[7].data||[]) as Audit[]);setKycSubs((results[8].data||[]) as Kyc[])},[])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));return supabase.auth.onAuthStateChange((_e,s)=>setSession(s)).data.subscription.unsubscribe},[])
 useEffect(()=>{if(!session){setAllowed(false);return}(async()=>{const{data}=await supabase.from('profiles').select('role').eq('id',session.user.id).single();setAllowed(data?.role==='admin');if(data?.role==='admin')load()})()},[session,load])
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');const{error:e1}=await supabase.auth.signInWithPassword({email,password});if(e1)setError(e1.message);setBusy(false)}
 const proof=async(path:string)=>{const{data,error:e}=await supabase.storage.from('payment-proofs').createSignedUrl(path,120);if(e)return setError(e.message);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 const review=async(kind:'payment'|'withdrawal',id:string,status:'approved'|'rejected'|'paid')=>{const note=window.prompt(status==='rejected'?'কারণ লিখুন':'নোট (ঐচ্ছিক)')||null;setError('');if(kind==='payment'&&status==='approved'){const{error:e}=await supabase.rpc('approve_payment',{p_payment_id:id,p_note:note});if(e)return setError(e.message)}else{const{error:e}=await supabase.from(kind==='payment'?'payment_requests':'withdrawal_requests').update({status,admin_note:note,reviewed_by:session!.user.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(e)return setError(e.message);await supabase.from('admin_audit_logs').insert({admin_id:session!.user.id,action:status,entity_type:kind,entity_id:id,metadata:{note}})}load()}
 const kyc=async(id:string,status:'approved'|'rejected')=>{const note=window.prompt(status==='rejected'?'বাতিলের কারণ লিখুন':'যাচাই নোট')||null;if(status==='rejected'&&!note)return;const{error:e}=await supabase.rpc('review_kyc',{p_submission_id:id,p_status:status,p_note:note});if(e)setError(e.message);else load()}
 const hold=async(p:Profile)=>{const active=holds.some(h=>h.user_id===p.id&&h.active),reason=window.prompt(active?'Release করার কারণ লিখুন':'Hold করার স্পষ্ট কারণ লিখুন');if(!reason)return;const{error:e}=await supabase.rpc('set_compliance_hold',{p_user_id:p.id,p_active:!active,p_reason:reason});if(e)setError(e.message);else load()}
 const declare=async(p:Profile)=>{const amount=Number(window.prompt(`${p.full_name}-এর বাস্তবায়িত profit/loss amount লিখুন (ক্ষতি হলে minus)`));if(!amount)return;const basis=window.prompt('হিসাবের উৎস/ভিত্তি লিখুন (যেমন gold sale settlement)');if(!basis)return;const{error:e}=await supabase.rpc('declare_profit',{p_user_id:p.id,p_investment_id:null,p_amount:amount,p_basis:basis,p_period_start:null,p_period_end:null});if(e)setError(e.message);else load()}
 const customers=useMemo(()=>profiles.filter(p=>p.role==='customer'&&(`${p.full_name} ${p.phone||''}`).toLowerCase().includes(query.toLowerCase())),[profiles,query]),pendingP=payments.filter(x=>x.status==='pending').length,pendingW=withdrawals.filter(x=>x.status==='pending').length,totalPrincipal=investments.filter(x=>x.active).reduce((n,x)=>n+Number(x.principal),0),totalGold=investments.filter(x=>x.active).reduce((n,x)=>n+Number(x.gold_grams),0)
 if(!session||allowed===false)return <main className="admin-login"><form onSubmit={login}><div className="admin-seal">G</div><span>GOLD INVESTOR • SECURE ADMIN</span><h1>Admin Panel</h1><p>অনুমোদিত administrator account দিয়ে প্রবেশ করুন।</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="admin-error">{error}</div>}<button disabled={busy}>{busy?'যাচাই হচ্ছে…':'নিরাপদে লগইন করুন'}</button><a href="/">← ওয়েবসাইটে ফিরুন</a></form></main>
 if(allowed===null)return <div className="admin-loading">Admin access যাচাই হচ্ছে…</div>
 const customerRows=(actions:(p:Profile)=>React.ReactNode)=><div className="admin-list">{customers.map(p=><article key={p.id}><div><span className={`status ${p.kyc_status}`}>KYC {p.kyc_status}</span><h3>{p.full_name||'নাম নেই'}</h3><p>{p.phone||session.user.email||'যোগাযোগ নেই'}</p><small>Joined {new Date(p.created_at).toLocaleDateString('bn-BD')}</small></div><strong>{money(investments.filter(i=>i.user_id===p.id).reduce((n,i)=>n+Number(i.principal),0))}</strong><div className="admin-actions"><button onClick={()=>setSelectedCustomer(p)}>বিস্তারিত</button>{actions(p)}</div></article>)}</div>
 return <div className="admin-shell"><aside><div className="admin-brand"><i>G</i><b>Gold Investor</b><span>ADMIN CONTROL</span></div>{(Object.keys(labels) as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{labels[v]}{v==='payments'?<em>{pendingP}</em>:v==='withdrawals'?<em>{pendingW}</em>:null}</button>)}<a href="/">ওয়েবসাইট দেখুন</a><button className="admin-logout" onClick={()=>supabase.auth.signOut()}>লগআউট</button></aside><main><header><div><span>ADMIN OPERATIONS</span><h1>{labels[view]}</h1></div><button onClick={load}>↻ Refresh</button></header>{error&&<div className="admin-error">{error}{error.includes('schema cache')&&<small> — migration 202608100005 SQL Editor-এ Run করুন।</small>}</div>}
 {view==='dashboard'&&<><section className="admin-stats admin-stats-wide"><article><span>Customers</span><b>{customers.length}</b></article><article><span>Pending payments</span><b>{pendingP}</b></article><article><span>Pending withdrawals</span><b>{pendingW}</b></article><article><span>Active capital</span><b>{money(totalPrincipal)}</b></article><article><span>Total gold</span><b>{totalGold.toFixed(3)} g</b></article><article><span>Declared profit/loss</span><b>{money(profits.reduce((n,x)=>n+Number(x.amount),0))}</b></article><article><span>Compliance holds</span><b>{holds.filter(h=>h.active).length}</b></article></section><div className="admin-note">সব financial action audit log-এ সংরক্ষিত হয়। Profit কেবল যাচাইকৃত settlement/হিসাবের ভিত্তিতে declare করুন।</div></>}
 {(view==='customers'||view==='compliance'||view==='profits')&&<><input className="admin-search" placeholder="নাম বা ফোন দিয়ে customer খুঁজুন" value={query} onChange={e=>setQuery(e.target.value)}/>{view==='customers'&&customerRows(p=><><button onClick={()=>setView('holdings')}>হোল্ডিংস</button><button onClick={()=>declare(p)}>Profit</button></>)}{view==='compliance'&&customerRows(p=><button className={holds.some(h=>h.user_id===p.id&&h.active)?'approve':'reject'} onClick={()=>hold(p)}>{holds.some(h=>h.user_id===p.id&&h.active)?'Release hold':'Place hold'}</button>)}{view==='profits'&&customerRows(p=><button className="approve" onClick={()=>declare(p)}>Profit/loss declare</button>)}</>}
 {view==='kyc'&&<div className="admin-list kyc-admin-list">{kycSubs.length===0?<div className="admin-empty">কোনো যাচাই আবেদন নেই</div>:kycSubs.map(x=><article key={x.id}><div><span className={`status ${x.status}`}>{x.status}</span><h3>{x.profiles?.full_name||'Customer'} • {x.profiles?.phone||'ফোন নেই'}</h3><p>জন্ম: {x.date_of_birth} · পেশা: {x.occupation}</p><p>বর্তমান ঠিকানা: {x.present_address}</p><p>Nominee: {x.nominee_name} ({x.nominee_relation})</p><small>{new Date(x.submitted_at).toLocaleString('bn-BD')}</small></div><strong>VERIFY</strong><div className="admin-actions">{x.status==='pending'&&<><button className="approve" onClick={()=>kyc(x.id,'approved')}>Approve</button><button className="reject" onClick={()=>kyc(x.id,'rejected')}>Reject</button></>}</div></article>)}</div>}
 {view==='payments'&&<div className="admin-list">{payments.map(x=><article key={x.id}><div><span className={`status ${x.status}`}>{x.status}</span><h3>{x.profiles?.full_name||'Customer'} • {x.method}</h3><p>{x.profiles?.phone||'Phone unavailable'} · TXID: {x.transaction_id}</p><small>{new Date(x.created_at).toLocaleString('bn-BD')}</small></div><strong>{money(x.amount)}</strong><div className="admin-actions"><button onClick={()=>proof(x.proof_path)}>প্রমাণ</button>{x.status==='pending'&&<><button className="approve" onClick={()=>review('payment',x.id,'approved')}>Approve</button><button className="reject" onClick={()=>review('payment',x.id,'rejected')}>Reject</button></>}</div></article>)}</div>}
 {view==='holdings'&&<div className="admin-list">{investments.map(x=><article key={x.id}><div><span className="status approved">{x.active?'ACTIVE':'CLOSED'}</span><h3>{x.profiles?.full_name||'Customer'} • {x.plan_name}</h3><p>{Number(x.gold_grams).toFixed(3)} গ্রাম · ক্রয়মূল্য/ভরি {money(x.gold_price_per_bhori)}</p><small>{new Date(x.purchased_at).toLocaleString('bn-BD')}</small></div><strong>{money(x.principal)}</strong></article>)}</div>}
 {view==='withdrawals'&&<div className="admin-list">{withdrawals.map(x=><article key={x.id}><div><span className={`status ${x.status}`}>{x.status}</span><h3>{x.profiles?.full_name||'Customer'} • {x.investments?.plan_name||'Investment'}</h3><small>{new Date(x.created_at).toLocaleString('bn-BD')}</small></div><strong>{money(x.amount)}</strong><div className="admin-actions">{x.status==='pending'&&<><button className="approve" onClick={()=>review('withdrawal',x.id,'approved')}>Approve</button><button className="reject" onClick={()=>review('withdrawal',x.id,'rejected')}>Reject</button></>}{x.status==='approved'&&<button className="approve" onClick={()=>review('withdrawal',x.id,'paid')}>Mark paid</button>}</div></article>)}</div>}
 {view==='ledger'&&<div className="admin-table">{ledger.map(x=><div key={x.id}><b>{x.profiles?.full_name||'Customer'}</b><span>{x.entry_type}</span><span>{x.description}</span><strong className={x.amount>=0?'credit':'debit'}>{money(x.amount)}</strong><small>{new Date(x.created_at).toLocaleString('bn-BD')}</small></div>)}</div>}
 {view==='audit'&&<div className="admin-table">{audits.map(x=><div key={x.id}><b>{x.profiles?.full_name||'Admin'}</b><span>{x.action}</span><span>{x.entity_type} · {x.entity_id.slice(0,8)}</span><code>{JSON.stringify(x.metadata)}</code><small>{new Date(x.created_at).toLocaleString('bn-BD')}</small></div>)}</div>}
 {selectedCustomer&&(()=>{const p=selectedCustomer,inv=investments.filter(x=>x.user_id===p.id),pay=payments.filter(x=>x.user_id===p.id),pf=profits.filter(x=>x.user_id===p.id),activeHold=holds.some(x=>x.user_id===p.id&&x.active),principal=inv.reduce((n,x)=>n+Number(x.principal),0),grams=inv.reduce((n,x)=>n+Number(x.gold_grams),0),declared=pf.reduce((n,x)=>n+Number(x.amount),0);return <div className="admin-customer-modal" onMouseDown={e=>e.currentTarget===e.target&&setSelectedCustomer(null)}><section className="admin-customer-panel"><button className="close" onClick={()=>setSelectedCustomer(null)}>×</button><span className={`status ${p.kyc_status}`}>KYC {p.kyc_status}</span><h2>{p.full_name||'নাম নেই'}</h2><p>{p.phone||'ফোন নেই'} · Account ID: {p.id}</p><div className="customer-summary"><div><span>Approved deposit</span><b>{money(pay.filter(x=>x.status==='approved').reduce((n,x)=>n+Number(x.amount),0))}</b></div><div><span>Active principal</span><b>{money(principal)}</b></div><div><span>Gold holding</span><b>{grams.toFixed(3)} g</b></div><div><span>Declared profit/loss</span><b>{money(declared)}</b></div><div><span>Pending payments</span><b>{pay.filter(x=>x.status==='pending').length}</b></div><div><span>Investments</span><b>{inv.length}</b></div><div><span>Compliance</span><b>{activeHold?'HOLD':'Clear'}</b></div><div><span>Joined</span><b>{new Date(p.created_at).toLocaleDateString('bn-BD')}</b></div></div><div className="customer-actions"><button onClick={()=>{setSelectedCustomer(null);setView('kyc')}}>KYC application</button><button onClick={()=>declare(p)}>Profit/loss declare</button><button className={activeHold?'':'danger'} onClick={()=>hold(p)}>{activeHold?'Release compliance hold':'Place compliance hold'}</button><button onClick={()=>{setSelectedCustomer(null);setQuery(p.phone||p.full_name);setView('payments')}}>Payments দেখুন</button></div><div className="admin-note">Account balance সরাসরি edit করা হয় না। Approved payment, gold purchase, verified profit/loss ও paid withdrawal-এর ledger থেকেই balance তৈরি হবে।</div></section></div>})()}
 </main></div>
}
